### ISSUE TITLE
Utilizar variable de entorno en lugar de http:localhost:5005

### ISSUE THREAD

**Issue by HarlandLohora** [alexiztg/rentame-client#1]
https://github.com/alexiztg/rentame-client/blob/5c7e3d5dd91c339f60b0c1055fb81db31499c0dd/src/pages/RentListPage/index.jsx#L28

**Comment by alexiztg** [comment]
![image](https://user-images.githubusercontent.com/33494866/207458974-4f485d99-a5d2-4320-a454-7f306fbdd9f6.png)
Listo, ya quedo la Variable de entorno
