### ISSUE TITLE
Actualizar el content del meta tag

### ISSUE THREAD

**Issue by HarlandLohora** [alexiztg/rentame-client#2]
https://github.com/alexiztg/rentame-client/blob/5c7e3d5dd91c339f60b0c1055fb81db31499c0dd/public/index.html#L10

**Comment by alexiztg** [comment]
![image](https://user-images.githubusercontent.com/33494866/207459893-90e510bf-9a39-46d9-b5d1-dca6ee30bc73.png)
Listo
